package Money.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CurrencyDefTable_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CurrencyDefTable_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Money.structure.CurrencyDefTable";
  }
}
