package Money.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Type_BehaviorDescriptor;

public class MoneyConversionType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public MoneyConversionType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Money.structure.MoneyConversionType";
  }
}
