package Money.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class MoneyLiteral_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getVariableExpectedName_1213877519781(SNode thisNode) {
    String text;
    switch (SPropertyOperations.getInteger(thisNode, "amount")) {
      case 10:
        text = "ten";
        break;
      case 20:
        text = "twenty";
        break;
      case 30:
        text = "thirty";
        break;
      default:
        text = "cash";
    }
    text += SLinkOperations.getTarget(thisNode, "unit", false);
    return text;
  }
}
