package Money.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Type_BehaviorDescriptor;

public class MoneyType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public MoneyType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Money.structure.MoneyType";
  }
}
