package Money.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class MoneyLiteral_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public MoneyLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Money.structure.MoneyLiteral";
  }
}
