package Money.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Type_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IType_BehaviorDescriptor;

public class MoneyType_BehaviorDescriptor extends Type_BehaviorDescriptor implements IType_BehaviorDescriptor {
  public MoneyType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Money.structure.MoneyType";
  }
}
