package Money.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class MoneyLiteral_Constraints extends BaseConstraintsDescriptor {
  public MoneyLiteral_Constraints() {
    super("Money.structure.MoneyLiteral");
  }
}
