package MoneyRuntime.classes;

/*Generated by MPS */

import java.math.BigDecimal;

public class Money {
  private BigDecimal myAmount;
  private String myCurrence;

  public Money(BigDecimal amount, String currency) {
    this.setAmount(amount);
    this.setCurrence(currency);
  }

  public Money(int amount, String currency) {
    this.setAmount(new BigDecimal(amount));
    this.setCurrence(currency);
  }

  public Money to(String targetCurrency) {
    return new Money(this.getAmount(), targetCurrency);
  }

  @Override
  public String toString() {
    return this.getAmount() + " " + this.getCurrence();
  }

  public BigDecimal getAmount() {
    return this.myAmount;
  }

  private void setAmount(BigDecimal value) {
    this.myAmount = value;
  }

  public String getCurrence() {
    return this.myCurrence;
  }

  private void setCurrence(String value) {
    this.myCurrence = value;
  }
}
