package STM.scripts;

/*Generated by MPS */

import jetbrains.mps.lang.script.runtime.BaseMigrationScript;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.lang.script.runtime.AbstractMigrationRefactoring;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class FFF_MigrationScript extends BaseMigrationScript {
  public FFF_MigrationScript(IOperationContext operationContext) {
    super("A nice script");
    this.addRefactoring(new AbstractMigrationRefactoring(operationContext) {
      public String getName() {
        return "Round-up discount";
      }

      public String getAdditionalInfo() {
        return "Round-up discount";
      }

      public String getFqNameOfConceptToSearchInstances() {
        return "STM.structure.AbsoluteDiscountValue";
      }

      public boolean isApplicableInstanceNode(SNode node) {
        return SPropertyOperations.getInteger(node, "value") == 9;
      }

      public void doUpdateInstanceNode(SNode node) {
        SPropertyOperations.set(node, "value", "" + 10);
      }

      public boolean isShowAsIntention() {
        return true;
      }
    });
  }
}
