package STM.sandbox.sandbox;

/*Generated by MPS */

import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;

public class DecisionSample {
  public DecisionSample() {
  }

  public int main_0() {
  }

  public static void main(String[] args) {
    Map<String, Object> person = MapSequence.fromMap(new HashMap<String, Object>());
    MapSequence.fromMap(person).put("name", "Joe");
    MapSequence.fromMap(person).put("age", 29);
    MapSequence.fromMap(person).put("gender", "male");

    int discount = main_0();

    System.out.println("Value: " + discount);
  }

  public static boolean isBaby(Map<String, Object> person) {
    return (Integer) MapSequence.fromMap(person).get("age") <= 2;
  }

  public static boolean isChild(Map<String, Object> person) {
    return (Integer) MapSequence.fromMap(person).get("age") < 18 && (Integer) MapSequence.fromMap(person).get("age") > 2;
  }

  public static boolean isAdult(Map<String, Object> person) {
    return (Integer) MapSequence.fromMap(person).get("age") <= 60 && (Integer) MapSequence.fromMap(person).get("age") >= 18;
  }

  public static boolean isRetired(Map<String, Object> person) {
    return (Integer) MapSequence.fromMap(person).get("age") > 60;
  }

  public static boolean isMale(Map<String, Object> person) {
    if ((String) MapSequence.fromMap(person).get("gender") == "male") {
      return true;
    }
    return false;
  }

  public static boolean isFemale(Map<String, Object> person) {
    return !(isMale(person));
  }
}
