package STM.sandbox.sandbox;

/*Generated by MPS */


public class IfSample {
  public IfSample() {
  }

  public static void main(String[] args) {
    if (true) {
      int value1 = 10;
      System.out.println("Result: " + value1);
      System.out.println("1");
      System.out.println("2");
      System.out.println("3");
      System.out.println("4");
    } else {
      int value2 = 20;
      System.out.println("Alternative result: " + value2);
      System.out.println("Foo");
      System.out.println("Bar");
    }
  }
}
