package STM.sandbox.sandbox;

/*Generated by MPS */


public class IfSample {
  public IfSample() {
  }

  public static void main(String[] args) {
    if (args.length > 1) {
      int value1 = Integer.parseInt(args[0]);
      int value2 = Integer.parseInt(args[1]);
      System.out.println("Result: " + (value1 + value2));
      System.out.println("Done");
    } else {
      System.out.println("We can add two numbers");
      System.out.println("Secify them as arguments");
      System.out.println("Done");
    }
  }
}
