package STM.sandbox.sandbox;

/*Generated by MPS */

import MoneyRuntime.classes.Money;

public class MoneySample {
  public MoneySample() {
  }

  public static void main(String[] args) {
    Money m = new Money(10, "EUR").plus(new Money(20, "EUR"));
    System.out.println("Money " + m);
  }
}
