package STM.sandbox.sandbox;

/*Generated by MPS */

import org.multiverse.api.StmUtils;
import org.multiverse.api.closures.AtomicClosure;
import org.multiverse.api.Transaction;

public class Sample {
  private String title;

  public Sample(final String title) {
    this.title = title;
  }

  @Override
  public String toString() {
    return title;
  }

  public static void main(final String[] args) {
    new Thread(new Runnable() {
      public void run() {
        if (!(args.length != 0)) {
          int result = StmUtils.execute(new AtomicClosure<Integer>() {
            public Integer execute(Transaction p0) throws Exception {
              final String s = Sample.create();
              Sample demo = new Sample(s);
              System.out.println("Title: " + demo.title);
              return 10;
            }
          });
          System.out.println("Result: " + result);
        }
      }
    }).start();
  }

  private static String create() {
    return "Demo";
  }
}
