package STM.sandbox.sandbox;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.internal.collections.runtime.ISelector;

public class Test {
  private static long counter = 0;

  public Test() {
  }

  public static void main(String[] args) throws Exception {
    List<String> friends = ListSequence.fromListAndArray(new ArrayList<String>(), "Joe", "Dave", "Alice", "Susan", "John");
    Iterable<String> jFriends = ListSequence.fromList(friends).where(new IWhereFilter<String>() {
      public boolean accept(String it) {
        return it.startsWith("J");
      }
    }).select(new ISelector<String, String>() {
      public String select(String it) {
        return it.toUpperCase();
      }
    });
    System.out.println("Friends: " + jFriends);
  }
}
