package STM.behavior;

/*Generated by MPS */


public class AbsoluteDiscountValue_BehaviorDescriptor extends DiscountValue_BehaviorDescriptor {
  public AbsoluteDiscountValue_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.AbsoluteDiscountValue";
  }
}
