package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.closures.behavior.ClosureLiteral_BehaviorDescriptor;

public class AClosureLiteral_BehaviorDescriptor extends ClosureLiteral_BehaviorDescriptor {
  public AClosureLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.AClosureLiteral";
  }
}
