package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class AConcept_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AConcept_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.AConcept";
  }
}
