package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.closures.behavior.ClosureLiteral_BehaviorDescriptor;

public class AsyncClosureExecution_BehaviorDescriptor extends ClosureLiteral_BehaviorDescriptor {
  public AsyncClosureExecution_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.AsyncClosureExecution";
  }
}
