package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.closures.behavior.ClosureLiteral_BehaviorDescriptor;

public class AtomicClosureLiteral_BehaviorDescriptor extends ClosureLiteral_BehaviorDescriptor {
  public AtomicClosureLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.AtomicClosureLiteral";
  }
}
