package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class AtomicExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public AtomicExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.AtomicExpression";
  }
}
