package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Set;
import java.util.HashSet;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;
import jetbrains.mps.smodel.SReference;
import jetbrains.mps.smodel.SModelReference;
import jetbrains.mps.smodel.SNodeId;

public class AtomicExpression_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String call_foo_5375423026569759239(SNode thisNode) {
    SNode expression = thisNode;
    expression.getId();
    SNode bar = expression;
    int v = 10;
    SNode node = new AtomicExpression_Behavior.QuotationClass_drqqyf_a0a4a1().createNode("" + v);

    return "askdhjkf";
  }

  public static class QuotationClass_drqqyf_a0a4a1 {
    public QuotationClass_drqqyf_a0a4a1() {
    }

    public SNode createNode(Object parameter_15) {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      SNode quotedNode_2 = null;
      SNode quotedNode_3 = null;
      SNode quotedNode_4 = null;
      SNode quotedNode_5 = null;
      SNode quotedNode_6 = null;
      SNode quotedNode_7 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.closures.structure.ClosureLiteral", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_8 = quotedNode_1;
        {
          quotedNode_2 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.ParameterDeclaration", null, GlobalScope.getInstance(), false);
          SNode quotedNode1_9 = quotedNode_2;
          quotedNode1_9.setProperty("name", "a");
          {
            quotedNode_4 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.IntegerType", null, GlobalScope.getInstance(), false);
            SNode quotedNode1_10 = quotedNode_4;
            quotedNode_2.addChild("type", quotedNode1_10);
          }
          quotedNode_1.addChild("parameter", quotedNode1_9);
        }
        {
          quotedNode_3 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.StatementList", null, GlobalScope.getInstance(), false);
          SNode quotedNode1_11 = quotedNode_3;
          {
            quotedNode_5 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.ExpressionStatement", null, GlobalScope.getInstance(), false);
            SNode quotedNode1_12 = quotedNode_5;
            {
              quotedNode_6 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.StaticMethodCall", null, GlobalScope.getInstance(), false);
              SNode quotedNode1_13 = quotedNode_6;
              quotedNode1_13.addReference(SReference.create("baseMethodDeclaration", quotedNode1_13, SModelReference.fromString("f:java_stub#6354ebe7-c22a-4a0f-ac54-50b52ab9b065#java.lang(JDK/java.lang@java_stub)"), SNodeId.fromString("~Integer.parseInt(java.lang.String):int")));
              quotedNode1_13.addReference(SReference.create("classConcept", quotedNode1_13, SModelReference.fromString("f:java_stub#6354ebe7-c22a-4a0f-ac54-50b52ab9b065#java.lang(JDK/java.lang@java_stub)"), SNodeId.fromString("~Integer")));
              {
                quotedNode_7 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.StringLiteral", null, GlobalScope.getInstance(), false);
                SNode quotedNode1_14 = quotedNode_7;
                quotedNode1_14.setProperty("value", (String) parameter_15);
                quotedNode_6.addChild("actualArgument", quotedNode1_14);
              }
              quotedNode_5.addChild("expression", quotedNode1_13);
            }
            quotedNode_3.addChild("statement", quotedNode1_12);
          }
          quotedNode_1.addChild("body", quotedNode1_11);
        }
        result = quotedNode1_8;
      }
      return result;
    }
  }
}
