package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class AtomicBlock_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public AtomicBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.AtomicBlock";
  }
}
