package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CConcept_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CConcept_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.CConcept";
  }
}
