package STM.behavior;

/*Generated by MPS */


public class CrossSellDiscountRule_BehaviorDescriptor extends DiscountRule_BehaviorDescriptor {
  public CrossSellDiscountRule_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.CrossSellDiscountRule";
  }
}
