package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class DiscountRule_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DiscountRule_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.DiscountRule";
  }
}
