package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class DiscountValue_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DiscountValue_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.DiscountValue";
  }
}
