package STM.behavior;

/*Generated by MPS */


public class PercentDiscountValue_BehaviorDescriptor extends DiscountValue_BehaviorDescriptor {
  public PercentDiscountValue_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.PercentDiscountValue";
  }
}
