package STM.behavior;

/*Generated by MPS */


public class PromotionalDiscountRule_BehaviorDescriptor extends DiscountRule_BehaviorDescriptor {
  public PromotionalDiscountRule_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.PromotionalDiscountRule";
  }
}
