package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class URL_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public URL_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.URL";
  }
}
