package STM.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class VolumeRank_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public VolumeRank_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.VolumeRank";
  }
}
