package STM.behavior;

/*Generated by MPS */


public class VolumeDiscountRule_BehaviorDescriptor extends DiscountRule_BehaviorDescriptor {
  public VolumeDiscountRule_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "STM.structure.VolumeDiscountRule";
  }
}
