package STM.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class CreateDefaultVolumeDiscount_Intention extends BaseIntention implements Intention {
  public CreateDefaultVolumeDiscount_Intention() {
  }

  public String getConcept() {
    return "STM.structure.DiscountRuleSet";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "Create Default Volume Discount";
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SNode rule = SNodeFactoryOperations.createNewNode("STM.structure.VolumeDiscountRule", null);
    ListSequence.fromList(SLinkOperations.getTargets(rule, "ranks", true)).clear();
    SNode rank = SNodeFactoryOperations.createNewNode("STM.structure.VolumeRank", null);
    SNode percentDiscountValue = SNodeFactoryOperations.createNewNode("STM.structure.PercentDiscountValue", null);
    SPropertyOperations.set(percentDiscountValue, "percent", "" + 0);
    SPropertyOperations.set(rank, "limit", "" + 10);
    SLinkOperations.setTarget(rank, "value", percentDiscountValue, true);
    ListSequence.fromList(SLinkOperations.getTargets(rule, "ranks", true)).addElement(rank);

    rank = SNodeFactoryOperations.createNewNode("STM.structure.VolumeRank", null);
    percentDiscountValue = SNodeFactoryOperations.createNewNode("STM.structure.PercentDiscountValue", null);
    SPropertyOperations.set(percentDiscountValue, "percent", "" + 5);
    SPropertyOperations.set(rank, "limit", "" + 20);
    SLinkOperations.setTarget(rank, "value", percentDiscountValue, true);
    ListSequence.fromList(SLinkOperations.getTargets(rule, "ranks", true)).addElement(rank);

    rank = SNodeFactoryOperations.createNewNode("STM.structure.VolumeRank", null);
    percentDiscountValue = SNodeFactoryOperations.createNewNode("STM.structure.PercentDiscountValue", null);
    SPropertyOperations.set(percentDiscountValue, "percent", "" + 10);
    SPropertyOperations.set(rank, "limit", "" + 30);
    SLinkOperations.setTarget(rank, "value", percentDiscountValue, true);
    ListSequence.fromList(SLinkOperations.getTargets(rule, "ranks", true)).addElement(rank);

    ListSequence.fromList(SLinkOperations.getTargets(node, "rules", true)).addElement(rule);
  }

  public String getLocationString() {
    return "STM.intentions";
  }
}
