package STM.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;

public class UnwrapAtomicBlock_Intention extends BaseIntention implements Intention {
  public UnwrapAtomicBlock_Intention() {
  }

  public String getConcept() {
    return "STM.structure.AtomicBlock";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return true;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "Unwrap Atomic Block";
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(this.isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }

  public boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    List<SNode> selectedNodes = (List<SNode>) editorContext.getSelectedNodes();
    SNode atomicBlock = SNodeOperations.getAncestor(ListSequence.fromList(selectedNodes).first(), "STM.structure.AtomicBlock", true, false);
    return atomicBlock == node;
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SNode atomicBlock = node;
    if (SNodeOperations.isInstanceOf(SNodeOperations.getParent(atomicBlock), "jetbrains.mps.baseLanguage.structure.StatementList")) {
      final SNode statementList = SNodeOperations.cast(SNodeOperations.getParent(atomicBlock), "jetbrains.mps.baseLanguage.structure.StatementList");
      final Wrappers._int index = new Wrappers._int(ListSequence.fromList(SLinkOperations.getTargets(statementList, "statement", true)).indexOf(atomicBlock));
      ListSequence.fromList(SLinkOperations.getTargets(statementList, "statement", true)).removeElementAt(index.value);
      ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(atomicBlock, "body", true), "statement", true)).visitAll(new IVisitor<SNode>() {
        public void visit(SNode it) {
          ListSequence.fromList(SLinkOperations.getTargets(statementList, "statement", true)).insertElement(index.value, it);
          index.value += 1;
        }
      });
    } else {
      SNode statement = SNodeFactoryOperations.replaceWithNewChild(atomicBlock, "jetbrains.mps.baseLanguage.structure.BlockStatement");
      SLinkOperations.setTarget(statement, "statements", SLinkOperations.getTarget(atomicBlock, "body", true), true);
    }
    SNodeOperations.deleteNode(atomicBlock);
  }

  public String getLocationString() {
    return "STM.intentions";
  }
}
