package DecisionTable.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class DecisionTable_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.addNewChild(thisNode, "rowHeaders", "jetbrains.mps.baseLanguage.structure.Expression");
    SLinkOperations.addNewChild(thisNode, "rowHeaders", "jetbrains.mps.baseLanguage.structure.Expression");
    SLinkOperations.addNewChild(thisNode, "colHeaders", "jetbrains.mps.baseLanguage.structure.Expression");
    SLinkOperations.addNewChild(thisNode, "colHeaders", "jetbrains.mps.baseLanguage.structure.Expression");
    SLinkOperations.addNewChild(thisNode, "resultValues", "jetbrains.mps.baseLanguage.structure.Expression");
    SLinkOperations.addNewChild(thisNode, "resultValues", "jetbrains.mps.baseLanguage.structure.Expression");
    SLinkOperations.addNewChild(thisNode, "resultValues", "jetbrains.mps.baseLanguage.structure.Expression");
    SLinkOperations.addNewChild(thisNode, "resultValues", "jetbrains.mps.baseLanguage.structure.Expression");
  }
}
