package DecisionTable.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class DecisionTable_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public DecisionTable_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DecisionTable.structure.DecisionTable";
  }
}
