package SampleExtensions.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class FalseFlow extends Flow {
  public static final String concept = "SampleExtensions.structure.FalseFlow";

  public FalseFlow(SNode node) {
    super(node);
  }

  public static FalseFlow newInstance(SModel sm, boolean init) {
    return (FalseFlow) SModelUtil_new.instantiateConceptDeclaration("SampleExtensions.structure.FalseFlow", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static FalseFlow newInstance(SModel sm) {
    return FalseFlow.newInstance(sm, false);
  }
}
