package SampleExtensions.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.StatementList;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Flow extends StatementList {
  public static final String concept = "SampleExtensions.structure.Flow";
  public static final String CPR_Title = "title";

  public Flow(SNode node) {
    super(node);
  }

  public static Flow newInstance(SModel sm, boolean init) {
    return (Flow) SModelUtil_new.instantiateConceptDeclaration("SampleExtensions.structure.Flow", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Flow newInstance(SModel sm) {
    return Flow.newInstance(sm, false);
  }
}
