package SampleExtensions.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class SampleExtensions_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("67b828fd-8fbc-4496-b7f7-8b64ac097c62(SampleExtensions)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
