package STM.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AbsoluteDiscountValue extends DiscountValue {
  public static final String concept = "STM.structure.AbsoluteDiscountValue";
  public static final String VALUE = "value";

  public AbsoluteDiscountValue(SNode node) {
    super(node);
  }

  public int getValue() {
    return this.getIntegerProperty(AbsoluteDiscountValue.VALUE);
  }

  public void setValue(int value) {
    this.setIntegerProperty(AbsoluteDiscountValue.VALUE, value);
  }

  public static AbsoluteDiscountValue newInstance(SModel sm, boolean init) {
    return (AbsoluteDiscountValue) SModelUtil_new.instantiateConceptDeclaration("STM.structure.AbsoluteDiscountValue", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AbsoluteDiscountValue newInstance(SModel sm) {
    return AbsoluteDiscountValue.newInstance(sm, false);
  }
}
