package STM.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.closures.structure.ClosureLiteral;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AClosureLiteral extends ClosureLiteral {
  public static final String concept = "STM.structure.AClosureLiteral";

  public AClosureLiteral(SNode node) {
    super(node);
  }

  public static AClosureLiteral newInstance(SModel sm, boolean init) {
    return (AClosureLiteral) SModelUtil_new.instantiateConceptDeclaration("STM.structure.AClosureLiteral", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AClosureLiteral newInstance(SModel sm) {
    return AClosureLiteral.newInstance(sm, false);
  }
}
