package STM.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.closures.structure.ClosureLiteral;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AtomicClosureLiteral extends ClosureLiteral {
  public static final String concept = "STM.structure.AtomicClosureLiteral";

  public AtomicClosureLiteral(SNode node) {
    super(node);
  }

  public static AtomicClosureLiteral newInstance(SModel sm, boolean init) {
    return (AtomicClosureLiteral) SModelUtil_new.instantiateConceptDeclaration("STM.structure.AtomicClosureLiteral", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AtomicClosureLiteral newInstance(SModel sm) {
    return AtomicClosureLiteral.newInstance(sm, false);
  }
}
