package STM.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CrossSellDiscountRule extends DiscountRule {
  public static final String concept = "STM.structure.CrossSellDiscountRule";
  public static final String CROSS_PRODUCT = "crossProduct";
  public static final String DISCOUNT = "discount";

  public CrossSellDiscountRule(SNode node) {
    super(node);
  }

  public String getCrossProduct() {
    return this.getProperty(CrossSellDiscountRule.CROSS_PRODUCT);
  }

  public void setCrossProduct(String value) {
    this.setProperty(CrossSellDiscountRule.CROSS_PRODUCT, value);
  }

  public DiscountValue getDiscount() {
    return (DiscountValue) this.getChild(DiscountValue.class, CrossSellDiscountRule.DISCOUNT);
  }

  public void setDiscount(DiscountValue node) {
    super.setChild(CrossSellDiscountRule.DISCOUNT, node);
  }

  public static CrossSellDiscountRule newInstance(SModel sm, boolean init) {
    return (CrossSellDiscountRule) SModelUtil_new.instantiateConceptDeclaration("STM.structure.CrossSellDiscountRule", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CrossSellDiscountRule newInstance(SModel sm) {
    return CrossSellDiscountRule.newInstance(sm, false);
  }
}
