package STM.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DiscountRule extends BaseConcept {
  public static final String concept = "STM.structure.DiscountRule";

  public DiscountRule(SNode node) {
    super(node);
  }

  public static DiscountRule newInstance(SModel sm, boolean init) {
    return (DiscountRule) SModelUtil_new.instantiateConceptDeclaration("STM.structure.DiscountRule", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DiscountRule newInstance(SModel sm) {
    return DiscountRule.newInstance(sm, false);
  }
}
