package STM.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DiscountValue extends BaseConcept {
  public static final String concept = "STM.structure.DiscountValue";

  public DiscountValue(SNode node) {
    super(node);
  }

  public static DiscountValue newInstance(SModel sm, boolean init) {
    return (DiscountValue) SModelUtil_new.instantiateConceptDeclaration("STM.structure.DiscountValue", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DiscountValue newInstance(SModel sm) {
    return DiscountValue.newInstance(sm, false);
  }
}
