package STM.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PercentDiscountValue extends DiscountValue {
  public static final String concept = "STM.structure.PercentDiscountValue";
  public static final String PERCENT = "percent";

  public PercentDiscountValue(SNode node) {
    super(node);
  }

  public int getPercent() {
    return this.getIntegerProperty(PercentDiscountValue.PERCENT);
  }

  public void setPercent(int value) {
    this.setIntegerProperty(PercentDiscountValue.PERCENT, value);
  }

  public static PercentDiscountValue newInstance(SModel sm, boolean init) {
    return (PercentDiscountValue) SModelUtil_new.instantiateConceptDeclaration("STM.structure.PercentDiscountValue", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PercentDiscountValue newInstance(SModel sm) {
    return PercentDiscountValue.newInstance(sm, false);
  }
}
