package STM.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PromotionalDiscountRule extends DiscountRule {
  public static final String concept = "STM.structure.PromotionalDiscountRule";
  public static final String DISCOUNT = "discount";

  public PromotionalDiscountRule(SNode node) {
    super(node);
  }

  public DiscountValue getDiscount() {
    return (DiscountValue) this.getChild(DiscountValue.class, PromotionalDiscountRule.DISCOUNT);
  }

  public void setDiscount(DiscountValue node) {
    super.setChild(PromotionalDiscountRule.DISCOUNT, node);
  }

  public static PromotionalDiscountRule newInstance(SModel sm, boolean init) {
    return (PromotionalDiscountRule) SModelUtil_new.instantiateConceptDeclaration("STM.structure.PromotionalDiscountRule", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PromotionalDiscountRule newInstance(SModel sm) {
    return PromotionalDiscountRule.newInstance(sm, false);
  }
}
