package STM.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class STM_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("be19a6e9-e972-4c4e-867f-04466d2dde44(STM)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
