package SampleExtensions.behavior;

/*Generated by MPS */


public class FalseFlow_BehaviorDescriptor extends Flow_BehaviorDescriptor {
  public FalseFlow_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "SampleExtensions.structure.FalseFlow";
  }
}
