package SampleExtensions.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.StatementList_BehaviorDescriptor;

public abstract class Flow_BehaviorDescriptor extends StatementList_BehaviorDescriptor {
  public Flow_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "SampleExtensions.structure.Flow";
  }
}
