package SampleExtensions.behavior;

/*Generated by MPS */


public class TrueFlow_BehaviorDescriptor extends Flow_BehaviorDescriptor {
  public TrueFlow_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "SampleExtensions.structure.TrueFlow";
  }
}
