package SampleExtensions.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class UnlessStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public UnlessStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "SampleExtensions.structure.UnlessStatement";
  }
}
